// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvPM_rsopGDREEYbfwtANUUHB4aOkAXgQ',
    // ⚠️ TODO: Replace YOUR_WEB_APP_ID with actual web app ID from Firebase Console
    // 1. Go to Firebase Console → Project Settings
    // 2. Add a Web App (</> icon)
    // 3. Copy the appId and paste it here
    appId: '1:799480392221:web:YOUR_WEB_APP_ID',
    messagingSenderId: '799480392221',
    projectId: 'krushiai-e6a17',
    authDomain: 'krushiai-e6a17.firebaseapp.com',
    storageBucket: 'krushiai-e6a17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvPM_rsopGDREEYbfwtANUUHB4aOkAXgQ',
    appId: '1:799480392221:android:ec24b9331c21d20fa434f4',
    messagingSenderId: '799480392221',
    projectId: 'krushiai-e6a17',
    storageBucket: 'krushiai-e6a17.firebasestorage.app',
  );
}
